version: "3.7"
services:
  dashboard:
    build: 
      context: .
      args: 
        - 'API_HOST=http://cars.cprogroup.ru/api/rubetek/angular-testcase-list/'
    environment:
      - 'API_HOST=http://cars.cprogroup.ru/api/rubetek/angular-testcase-list/'
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"